name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zgldh/mqtt-quacker:$(date +%s)
    - name: Docker Action
      # You may pin to the exact commit or the version.
      # uses: zenato/docker-action@8309ea4d790d074676660449b9f2bcbcae25cdb9
      uses: zenato/docker-action@v1.0.0
      with:
        # Registry username
        username: zgldh
        # Registry password
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        # Repository on registry
        repository: zgldh/mqtt-quacker
        # Registry hostname
        #registry: # optional
        # Image tag
        #tag: # optional 
