name: Docker Image CI

on:
  create:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/checkout@v2
    - name: Docker Action
      # You may pin to the exact commit or the version.
      # uses: zenato/docker-action@8309ea4d790d074676660449b9f2bcbcae25cdb9
      uses: zenato/docker-action@v1.0.0
      with:
        # Registry username
        username: zgldh
        # Registry password
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        # Repository on registry
        repository: zgldh/mqtt-quacker
        # Registry hostname
        #registry: # optional
        # Image tag
        tag: ${{ steps.get_version.outputs.VERSION }}
